### ISSUE TITLE
Preview Demo not found.

### ISSUE THREAD

**Issue by tluanga34** [jessegreathouse/TinyEditor#16]
As per the readme instructions, the demo link provided http://sandbox.scriptiny.com/tinyeditor/ is not working.

**Comment by jessegreathouse** [comment]
I have no control or ownership of scriptiny.com (the site hosting the demo). If you would like to update the readme to remove that link, then I would be amenable to approving such a PR; however, scriptiny.com has gone off and back online periodically over the past 5 years, so I would urge you to wait and see if it comes back again. Closing this issue because fixing the demo site is not actionable by anyone affiliated with this github repository.
